#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-racc
Version  : 1.4.12
Release  : 8
URL      : https://rubygems.org/downloads/racc-1.4.12.gem
Source0  : https://rubygems.org/downloads/racc-1.4.12.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: rubygem-racc-bin
Requires: rubygem-racc-lib
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake-compiler
BuildRequires : rubygem-rdoc

%description
= Racc
* http://i.loveruby.net/en/projects/racc/
* http://racc.rubyforge.org/
== DESCRIPTION:

%package bin
Summary: bin components for the rubygem-racc package.
Group: Binaries

%description bin
bin components for the rubygem-racc package.


%package lib
Summary: lib components for the rubygem-racc package.
Group: Libraries

%description lib
lib components for the rubygem-racc package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n racc-1.4.12
gem spec %{SOURCE0} -l --ruby > rubygem-racc.gemspec

%build
gem build rubygem-racc.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
racc-1.4.12.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/racc-1.4.12
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/racc-1.4.12.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/racc-1.4.12/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/racc-1.4.12/gem_make.out
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/racc-1.4.12/mkmf.log
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/.gemtest
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ChangeLog
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/DEPENDS
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/README.ja.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/TODO
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/bin/racc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/bin/racc2y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/bin/y2racc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/.RUBYARCHDIR.-.racc.time
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/MANIFEST
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/com/headius/racc/Cparse.java
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/cparse.c
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/cparse.o
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/depend
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/fastcache/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/fastcache/fastcache.c
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/compat.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/debugflags.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/exception.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/grammar.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/grammarfileparser.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/info.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/iset.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/logfilegenerator.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/parser-text.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/parserfilegenerator.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/pre-setup
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/sourcetext.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/state.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/statetransitiontable.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/static.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/misc/dist.sh
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/en/NEWS.en.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/en/grammar.en.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/ja/NEWS.ja.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/ja/command.ja.html
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/ja/debug.ja.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/ja/grammar.ja.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/ja/index.ja.html
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/ja/parser.ja.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/rdoc/ja/usage.ja.html
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/array.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/array2.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/calc-ja.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/calc.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/conflict.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/hash.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/lalr.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/lists.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/syntax.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/sample/yyerr.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/tasks/doc.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/tasks/email.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/chk.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/conf.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/digraph.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/echk.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/err.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/expect.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/firstline.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/ichk.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/intp.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/mailp.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/newsyn.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/noend.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/nonass.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/normal.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/norule.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/nullbug1.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/nullbug2.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/opt.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/percent.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/recv.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/rrconf.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/scan.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/syntax.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/unterm.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/useless.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/assets/yyerr.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/bench.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/infini.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/scandata/brace
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/scandata/gvar
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/scandata/normal
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/scandata/percent
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/scandata/slash
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/src.intp
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/start.y
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/test_chk_y.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/test_grammar_file_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/test_racc_command.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/test_scan_y.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/test/testscanner.rb
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/web/racc.en.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/web/racc.ja.rhtml
/usr/lib64/ruby/gems/2.3.0/specifications/racc-1.4.12.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/racc
/usr/bin/racc2y
/usr/bin/y2racc

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/racc-1.4.12/racc/cparse.so
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/ext/racc/cparse.so
/usr/lib64/ruby/gems/2.3.0/gems/racc-1.4.12/lib/racc/cparse.so
